void displayTomImage(int x, int y);
void displayTomJerryImage(int x, int y);
void moveVerticalScreen(int width, int height , int x , int y);
void controlTomJerryImage(int x, int y);
void displayGameOverImage(int x, int y);
void displayGameWinImage(int x, int y);
void displayAuthorsImage (int x, int y);
void displaySpaceShipImage(int x, int y);
void displayPlayerLife(int x,int y);
void clearPlayerLife(int x,int y);
void displaySpaceShipImageLevel2(int x, int y);
void displaySpaceShipImageLevel3(int x, int y);
void displaySpaceShipImageLevel4(int x, int y);
void displayWordPlayerLife(int x,int y);
void displayScore(int x, int y);
void displayScore0(int x, int y);
void displayScore1(int x, int y);
void displayScore2(int x, int y);
void displayScore3(int x, int y);
void displayScore4(int x, int y);
void displayScore5(int x, int y);
void displayScore6(int x, int y);
void displayScore7(int x, int y);
void displayScore8(int x, int y);
void displayScore9(int x, int y);
void clearScore(int num, int x, int y);
void displayExplosion(int x, int y);