int string_compare();
int string_length();
void string_to_lowercase();
void string_remove_extra_spaces();
void replace_multi_space_with_single_space();
void trim_trailing_string();
int string_contains();
int string_to_integer();
void string_split();
int array_length();
void integer_to_string(int n, char *str);
